[project]
name = "agent-engine-toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.15.1",
    "google-genai>=1.40.0",
    "pydantic>=2.12.5",
]
