[project]
name = "stock-terminal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anyio>=4.12.1",
    "fastapi>=0.123.10",
    "google-adk>=1.22.1",
    "httpx>=0.28.1",
    "httpx-sse>=0.4.3",
    "mcp>=1.25.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "uvicorn>=0.40.0",
    "yfinance>=1.0",
    "googlesearch-python>=1.2.3",
]
