[project]
name = "vertex-ai-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.132.0",
    "google-adk>=1.25.1",
    "google-auth>=2.48.0",
    "google-cloud-aiplatform>=1.138.0",
    "google-genai>=1.64.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "uvicorn>=0.41.0",
]
